### ISSUE TITLE
Firmware Build v0.38-1 fails

### ISSUE THREAD

**Issue by penguineer** [FreifunkMD/site-ffmd#104]
I tried to do a firmware build, but both available methods failed:
* Build according to https://github.com/FreifunkMD/site-ffmd/blob/master/README.md
* Build with docker: https://github.com/FreifunkMD/FFMD-Orga/issues/9#issuecomment-358083224

We need a step-by-step howto on sucessfully building the firmware, otherwise testing is really hard.

This blocks approval of #103 right now.

**Comment by christf** [comment]
I was able to successfully build the firmware using the docker approach:
* start the container
* run make update
* run bash buildOnly.sh

**Comment by penguineer** [comment]
Seemed to work for me as well, yesterday (until docker ran out of space).
I have to re-check.

Until now I started 5 approaches on 3 different systems and none worked.

**Comment by penguineer** [comment]
This seems to be happening on a specific machine. 
The issue is discussed there: https://github.com/FreifunkMD/gluon-docker/issues/2
