### ISSUE TITLE
Neue IP-Daten für gw2 eintragen

### ISSUE THREAD

**Issue by penguineer** [FreifunkMD/site-ffmd#130]
Es wird eine neue Maschine für gw2 mit geänderten IP-Daten geben. Diese müssen in die site.conf eingetragen werden.

**Comment by LeSpocky** [comment]
On Sat, Oct 20, 2018 at 04:21:13AM -0700, Stefan Haun wrote:
> Es wird eine neue Maschine für gw2 mit geänderten IP-Daten geben. Diese müssen in die site.conf eingetragen werden.

Kann man erst die neuen Daten (gw2 neu) hinzufügen und erstmal mit drei
eingetragenen Gateways fahren, auch wenn eins (gw2 alt) nicht
erreichbar ist, und dann später gw2 alt entfernen? Man muss die neue
Maschine ja nicht gleich (oder auch gar nicht) gw2 nennen?

**Comment by penguineer** [comment]
Ja, grundsätzlich ja. Praktisch haben wir gerade aber gar kein gw2, d.h. man kann den Namen dann auch wiederverwenden und spart sich den Aufwand, neue Einträge in DNS etc zu machen. Es ändern sich lediglich zwei IP-Adressen.

**Comment by penguineer** [comment]
Die Situation ist die, dass wir kein GW2 haben. Die Maschine lief nicht stabil und ist jetzt auch abgemeldet (effektiv ab 30.11.). Wir ersetzen also gw2 durch eine andere Maschine mit neuen IP-Daten.

**Comment by penguineer** [comment]
Beschluss:
* [ ] Feste IP-Daten aus site.conf entfernen
* [ ] Neue Maschine heißt auch gw2, wir haben nur das Gerät ersetzt

**Comment by penguineer** [comment]
Das alte Gateway heißt, solange es noch existiert, gw2-alt.md.freifunk.net

**Comment by penguineer** [comment]
Done.
