### ISSUE TITLE
config modus Formular anpassen

### ISSUE THREAD

**Issue by eriu** [FreifunkMD/site-ffmd#30]
da wir unsere Knotenregistrierung mit dem Formular aus Hamburg machen, wäre es vermutlich besser wenn wir dann Formularfelder (z.B. GPS) ausblenden die in dem Webformular eingetragen werden.

wir könnten z.B. die Packete aus Hamburg nutzen: https://github.com/freifunkhamburg/ffhh-packages
Der aktuelle ffhh-packages (master) ist für barrier breaker
der configmodus-split wird mit igluon 2014.4 eingebaut, ggf könnten wir das nutzen

**Comment by LeSpocky** [comment]
Hier wäre es tatsächlich gut, wie die Hamburger das mittlerweile gelöst haben. Die entsprechenden Anpassungen wären in v0.32 mit gluon 2015.1.x gut aufgehoben.

**Comment by LeSpocky** [comment]
Hamburg scheint unter https://formular.hamburg.freifunk.net/ das alte Registerformular und unter https://map.hamburg.freifunk.net/ ein angepassten Meshviewer zu verwenden. Wie bereits beim Treffen im Juli diskutiert, wäre ich dafür das Formular um- oder neu zu bauen und nur noch für den fastd-Key zu verwenden. Oder halt so wie FFM alle Keys erlauben und blacklist.

**Comment by LeSpocky** [comment]
Ohne jetzt den letzten Stand unser Diskussionen noch im Detail parat zu haben. Wie schon in #44 geschrieben, ist der Plan jetzt Koordinaten o.ä. auf dem Knoten einzutragen und das Formular nur noch zum Handhaben der fastd VPN Keys zu benutzen.
