### ISSUE TITLE
gateways umbenennen

### ISSUE THREAD

**Issue by LeSpocky** [FreifunkMD/site-ffmd#42]
gateways sollen umbenannt werden von *fastd1.md.freifunk.net* zu *gw1.md.freifunk.net* – das muss im DNS und in der site.conf geändert werden, letzteres erst nachdem die DNS das richtig auflösen.

**Comment by eriu** [comment]
soweit ich das sehe sind gw1. und gw2. im DNS richtig eingetragen

**Comment by eriu** [comment]
die Paderborner haben für ipv4 und ipv6 jeweils extra adressen eingetragen:
https://git.c3pb.de/freifunk-pb/site-ffpb/blob/master/site.conf

> gw01 = {
					-- public fastd key of the vpn server
					key = '97bc56ae561f67cfe15364134868c3553b5f1eab06f7bd9c5b93fbf280a52b51',
					-- remotes is an array of ways on how to reach the VPN server
					-- Use public addresses here, these addresses are used when the mesh might not be connected yet.
					-- format: '[|ipv4|ipv6] "hostname-or-ip-address" port 10000'
					remotes = {
						'ipv6 "v6.gw01.paderborn.freifunk.net" port 10000',
						'ipv4 "v4.gw01.paderborn.freifunk.net" port 10000',
						'ipv6 "2a01:4f8:190:2105::ff12" port 10000',
						'ipv4 "85.10.248.243" port 10000',
					},
				},

**Comment by LeSpocky** [comment]
Ich weiß, dass @apfohl dass schon im DNS eingetragen hatte. Da nochmal extra Adressen für v4 oder v6 zu nehmen, halte ich aber für sinnlos. Man kann doch für gw1.md.freifunk.net zwei Adressen hinterlegen, eine für v4 und eine für v6.

**Comment by LeSpocky** [comment]
See:

```
root@balkony:~# nslookup gw1.md.freifunk.net
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      gw1.md.freifunk.net
Address 1: 37.120.160.206 fastd1.md.freifunk.net
root@balkony:~# nslookup gw2.md.freifunk.net
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      gw2.md.freifunk.net
Address 1: 2a01:4a0:2002:2189::64 gw2.md.freifunk.net
Address 2: 130.185.109.142 gw2.md.freifunk.net
```

**Comment by eriu** [comment]
siehe https://github.com/FreifunkMD/site-ffmd/issues/46

**Comment by LeSpocky** [comment]
fixed by #49
