### ISSUE TITLE
remove some config packages

### ISSUE THREAD

**Issue by LeSpocky** [FreifunkMD/site-ffmd#44]
Um möglichst wenig Daten auf den Knoten liegen zu haben bzw. konfigurieren zu müssen und damit auch weniger Daten im A.L.F.R.E.D. rumfliegen zu haben, sollen folgende Pakete aus der Firmware wieder raus:
- gluon-config-mode-hostname
- gluon-config-mode-geo-location
- gluon-config-mode-contact-info

Hätte auch den Vorteil, dass Daten nicht doppelt gepflegt werden müssen auf den Knoten und auf dem Gateway.

**Comment by eriu** [comment]
wäre ggf. eine Überschneidung von #30

**Comment by LeSpocky** [comment]
Ich würde das gern nochmal neu diskutieren, ggf. auf dem nächsten Treffen. Bei wachsendem Netz wird es immer mehr Knoten ohne Uplink geben und da wären die Informationen vielleicht doch hilfreich?

**Comment by penguineer** [comment]
Dieses Issue kann IMHO geschlossen werden, oder? Es gibt den Verweis auf eine neue Diskussion und AFAIK wird das inzwischen auch anders gehandhabt.

**Comment by LeSpocky** [comment]
Ja richtig. Der letzte Stand war IIRC, dass die Daten auf dem Knoten eingetragen werden und das Formular wenn überhaupt nur noch zur Registrierung des fastd VPN Key dienen soll. Zumindest war es in der Praxis seit dem Umstieg auf die neue Karte ja auch so, dass für die Koordinaten eh nur die Daten vom Knoten selbst berücksichtigt wurden.
