### ISSUE TITLE
gateway per ipv6 erreichbar machen

### ISSUE THREAD

**Issue by eriu** [FreifunkMD/site-ffmd#46]
Unsere Gateways sind aktuell nicht erreichbar von einen (KD) Anschluss, der nur eine ipv6 Adresse bekommt.

**Comment by eriu** [comment]
also wir müssten die IPv6 Adressen ergänzen in der site.conf:
aktuell steht dort in etwa: remotes = {'ipv4 "gw1.md.freifunk.net" port 10000'},

**Comment by eriu** [comment]
das müsste so aussehen:
     peers = {
          peer1 = {
            key = '4cd9f8cafd8ee0b24378651252815ddc731d55c4db3c9644d8ee860ecc8df5d2',

            -- This is a list, so you might add multiple entries.
            remotes = {
            'ipv6 "gw1.md.freifunk.net" port 10000'
            'ipv6 "2a03:4000:6:30c3::32" port 10000'
            'ipv4 "gw1.md.freifunk.net" port 10000'
            'ipv4 "37.120.160.206" port 10000',
            },
          },
          peer2 = {
            key = '23731bc411ef17129163bfedc5ecc7f5df05d46fed0f56d92028d082704474be',
            -- You can also omit the ipv4 to allow both connection via ipv4 and ipv6
            remotes = {
            'ipv6 "gw2.md.freifunk.net" port 10000',
            'ipv6 "2a01:4a0:2002:2189::64" port 10000',
            'ipv4 "gw2.md.freifunk.net" port 10000',
            'ipv4 "130.185.109.142" port 10000',
            },
          },
        },

**Comment by LeSpocky** [comment]
Dem Hinweis aus #42 folgend schlage ich folgendes vor:

```
    peers = {
      peer1 = {
        key = '4cd9f8cafd8ee0b24378651252815ddc731d55c4db3c9644d8ee860ecc8df5d2',
        remotes = {
          '"gw1.md.freifunk.net" port 10000',
          'ipv6 "2a03:4000:6:30c3::32" port 10000',
          'ipv4 "37.120.160.206" port 10000'
        },
      },
      peer2 = {
        key = '23731bc411ef17129163bfedc5ecc7f5df05d46fed0f56d92028d082704474be',
        remotes = {
          '"gw2.md.freifunk.net" port 10000',
          'ipv6 "2a01:4a0:2002:2189::64" port 10000',
          'ipv4 "130.185.109.142" port 10000',
        },
       },
      },
```

**Comment by eriu** [comment]
da fehlt noch ein Komma oder eins ist zuviel?           
> 'ipv4 "37.120.160.206" port 10000' 
bzw.          
> 'ipv4 "130.185.109.142" port 10000',

**Comment by LeSpocky** [comment]
Ja, werde ich dann beim Einbauen drauf achten.

**Comment by LeSpocky** [comment]
siehe pr #51
