### ISSUE TITLE
rrd tools auf der Karte geht nicht

### ISSUE THREAD

**Issue by Hichi** [FreifunkMD/site-ffmd#47]
Das RRD Tool was einem die verbundenen Clients anzeigt, zeigt, zumindest bei mir, nur an, dass der Knoten offline ist. Wohingegen in der Karte n>=1 clients angezeigt werden.

**Comment by LeSpocky** [comment]
Danke für die Rückmeldung. Wir werden da vermutlich keine Energie mehr reinstecken. Der Plan ist auf https://github.com/tcatm/meshviewer umzusteigen und dann ist das hier nicht mehr relevant.

**Comment by LeSpocky** [comment]
Wäre für meshviewer auch interessant, funktioniert da laut @bastinat0r aber auch nicht. Ich wäre für eine andere Lösung, die noch mehr aus den vorhandenen Daten rausholt.

**Comment by eriu** [comment]
ein form von meshviwer wird mitlerweile unter https://github.com/plumpudding/hopglass weiterentwickelt, da kann man weitere featurerequests stellen
