### ISSUE TITLE
site.conf changes due to 802.11s support

### ISSUE THREAD

**Issue by eriu** [FreifunkMD/site-ffmd#60]
kam gerade auf der Gluon ML

Wichtig wäre dann zu testen ob man beide MeshInterfaces gleichzeitg fahren kann

We've just committed a site.conf-breaking change in regard to the
wireless config.
Make sure to read http://gluon.readthedocs.org/en/latest/user/site.html
and update your site.conf accordingly!

Support for 802.11s mesh interfaces has been added. Gluon now supports
three interface types: ap, ibss and mesh. All of them are now optional
and may be configured independently in site.conf.

A sample site.conf may look like this:

```
  wifi24 = {
       channel = 1,
       htmode = 'HT40+',
       ap = {
               ssid = 'luebeck.freifunk.net',
       },
       ibss = {
               ssid = '02:d1:11:37:fc:38',
               bssid = '02:d1:11:37:fc:38',
               mcast_rate = 12000,
       },
       mesh = {
               id = 'ffhl-mesh',
               mcast_rate = 12000,
       },
  },
```

**Comment by LeSpocky** [comment]
Das wird vermutlich mit gluon 2015.2.x eh kommen. Ich würd's gern erstmal nur intern testen wollen, da es zusätzlich auch openwrt cc schon ist.

**Comment by eriu** [comment]
ich hab einen entsprechenden Branch erstellt zum testen. Aktuell laufen bei mir 2 Knoten mit 11s im Mesh on WLAN: https://github.com/FreifunkMD/site-ffmd/tree/mesh-11s

* https://map.md.freifunk.net/#!v:m;n:60e327bdac74
* https://map.md.freifunk.net/#!v:m;n:e8de2765c250

**Comment by penguineer** [comment]
An gluon 2015.2.x sind wir nun schon vorbei (aktuell 2016.2.x). 

Ist dieses Issue noch relevant?

**Comment by LeSpocky** [comment]
Wenn ich mich richtig entsinne gibt es für das Mesh zwei Ansätze. Früher gab es nur ad-hoc und das ist auch das, was wir benutzen. Irgendwann wurde dann 802.11s unterstützt und ich glaube das will man auch haben, aber wir haben es nie wirklich ernsthaft versucht einzubauen, außer eben das, was hier im Ticket erwähnt ist. Man kann halt nicht einfach von ad-hoc auf 802.11s umschalten, weil sonst ggf. Mesh-only Knoten abgehängt werden.

**Comment by penguineer** [comment]
Okay. Dann ist das etwas, das @christf beim letzten Treffen tatsächlich in den Raum geworfen hatte. 
Ich lasse dieses Issue als Reminder offen und verschiebe es auf den later-Milestone.

**Comment by christf** [comment]
Parallelbetrieb geht, sollte aber nur kurz stattfinden weil es den management-traffic deutlich erhöht und dadurch das Netz deutlich sichtbar belastet. Der Umstieg ist ein breaking Change für Wifi Meshes.

**Comment by johannwagner** [comment]
Es wäre wohl wünschenswert, wenn wir den Parallelbetrieb möglichst kurz halten. Dabei bietet es sich an, dass wir dabei den Wechsel über die `v2017.x` nehmen, da dieser eh kurz sein soll.

**Comment by penguineer** [comment]
Wird so nicht gemacht, weil wir direkt auf Babel umsteigen wollen.
