### ISSUE TITLE
french translation

### ISSUE THREAD

**Issue by eriu** [FreifunkMD/site-ffmd#70]
see
- http://gluon.readthedocs.org/en/v2016.1/releases/v2016.1.html#french-translation
- https://github.com/freifunk-gluon/gluon/blob/master/docs/site-example/i18n/fr.po
- translate our english (https://github.com/FreifunkMD/site-ffmd/blob/master/i18n/en.po) oder german to french
- add register link

**Comment by penguineer** [comment]
Ticket wird geschlossen, weil sich dafür kein Maintainer gefunden hat.
