### ISSUE TITLE
Multi MTU Support

### ISSUE THREAD

**Issue by eriu** [FreifunkMD/site-ffmd#72]
Multi MTU Support
- Einbauen von https://github.com/freifunk-ffm/packages/tree/master/ffffm/ffffm-fastd-auto-mtu in unserer Config
- weitere Details unter https://forum.freifunk.net/t/multi-mtu-script/9071
- config aus ffm: https://github.com/freifunk-ffm/site-ffffm/blob/dev/site.mk

**Comment by eriu** [comment]
man kann auch mehrere Ports direkt in der site.conf angeben
zb
        remotes = {'ipv4 "gw1.md.freifunk.net" port 10000' , 'ipv4 "gw1.md.freifunk.net" port 10001'},
https://github.com/freifunk-ffm/packages/issues/3

**Comment by christf** [comment]
Am Ende ist eine MTU für clients sinnvoll. Komplexität ist der Feind.
