### ISSUE TITLE
modules for wifi failback

### ISSUE THREAD

**Issue by eriu** [FreifunkMD/site-ffmd#76]
- add modules to ffho
- and wifi fallback package
  https://git.c3pb.de/freifunk-pb/site-ffho/blob/stable/modules

**Comment by eriu** [comment]
die Packete liegen unter https://github.com/FreifunkMD/ffmd-packages

**Comment by christf** [comment]
upstream den autoupdater patchen halte ich für sinnvoll...

**Comment by penguineer** [comment]
Sollte im Rahmen von Gluon entwickelt werden, wir lösen das bei uns durch den Umstieg auf die Babel-Firmwae.
