### ISSUE TITLE
gluon 2016.2.1

### ISSUE THREAD

**Issue by eriu** [FreifunkMD/site-ffmd#82]
change site.mk and site.conf for http://gluon.readthedocs.io/en/v2016.1.6/releases/v2016.1.6.html

**Comment by eriu** [comment]
update: 2016.2.1 verfügbar http://gluon.readthedocs.io/en/v2016.2.1/

**Comment by eriu** [comment]
update: 2016.2.4 verfügbar https://gluon.readthedocs.io/en/v2016.2.4/releases/v2016.2.4.html

**Comment by eriu** [comment]
siehe https://github.com/FreifunkMD/site-ffmd/pull/90

**Comment by penguineer** [comment]
Ich schließe dieses Ticket mal, 
weiter geht es in #93.
