### ISSUE TITLE
Lizenz für Kartendarstellung ausgelaufen

### ISSUE THREAD

**Issue by penguineer** [FreifunkMD/site-ffmd#83]
Während der Knotenregistrierung wird eine Mini-Karte eingeblendet, auf der der Standort ausgewählt werden kann. Allerdings ist die Lizenz abgelaufen, sodass man dort nur noch den entsprechenden Hinweis sieht und die Koordinaten von anderer Stelle beziehen muss.

**Comment by johannwagner** [comment]
Dies scheint keine Lizenz zu sein. Wir sind aktuell knapp 140 Commits hinterm Master von Hamburg, vielleicht lässt sich das Problem hier durch ein Update lösen.

Meines Erachtens hat der Kartenanbieter hier den CDN gewechselt und deswegen geht da der Request auf den Kartenteil ins Leere. 
Von einem Lizenzkey oder ähnlichem steht allerdings in dem [Repo](https://github.com/freifunkhamburg/ffffng) von Hamburg nichts.

**Comment by johannwagner** [comment]
@penguineer Damit löst sich auch unsere Status-Mail-Problematik. Das scheint in Hamburg in den letzten 140 Commits auch passiert zu sein. [Beispiel](https://github.com/freifunkhamburg/ffffng#option-zum-automatischen-versand-von-monitoring-e-mails)

**Comment by johannwagner** [comment]
https://github.com/FreifunkMD/FFMD-Orga/issues/30

**Comment by penguineer** [comment]
Zu diesem Git-Repo gibt es tatsächlich einen Cron-Job, der alle 5 Minuten eine Systemmail erzeugt, wenn sich im Repo nichts geändert hat …

**Comment by penguineer** [comment]
Lese ich das richtig, dass wir dieses Tool eigentlich auch ablösen sollten?

**Comment by johannwagner** [comment]
### Git-Repo

Hat der Cronjob an der Stelle irgendwie einen tieferen Sinn?
Das Git-Repository hat einen Stand von 2014-12-29.. Ich weiß nicht, ob das noch benutzt wird. Dazu müsste man sich beim nächsten Hacktreffen mal zusammen setzen.

### Ablösung

Generell ist das Tool eigentlich ein Anti-Pattern zur Freifunk-Philosophie, da hier Daten zentral abgelegt werden und dies eigentlich so wenig wie möglich passieren sollte. Dies wisse auch die Hamburger und schreiben das ganz groß drüber.

Grundsätzlich wäre eine Migration von den Daten auf die Router durchaus sinnvoll und wichtig und richitg, allerdings scheint die Migration, ebenfalls laut Hamburg, nicht so einfach zu sein. Das Tool wird noch regelmäßig upgedatet, letzter Commit aufm Master is nen Monat her, also sollte hier kein Problem bestehen, einfach zu updaten. 'Letztes Update' in meinem Post beschreibt hier unseren Update-Stand.

**Comment by penguineer** [comment]
Ja, das ist definitiv ein Thema für das nächste Mal. Ggf. bringen wir das Tool erstmal auf den neusten Stand und überlegen uns dann, wie eine Migration aussehen könnte.

**Comment by christf** [comment]
um welche Daten geht es konkret?

**Comment by penguineer** [comment]
Die Registrierungs-Seite wird abgeschaltet, Firmware ist in #123 angepasst.
