### ISSUE TITLE
GLUON_REGION ist nicht definiert

### ISSUE THREAD

**Issue by LeSpocky** [FreifunkMD/site-ffmd#95]
Die Beispieldatei `docs/site-example/site.mk` in gluon v2016.1.x enthält:

```
# Region code required for some images; supported values: us eu
GLUON_REGION ?= eu
```

Das fehlt bei uns. Ggf. nochmal prüfen wofür das nötig ist und welchen Wert man da übernehmen will.

**Comment by johannwagner** [comment]
Ist im Pull-Request von mir gefixt.
Geht bei der Variable um die Sendeleistung von WLAN, wenn ich mich recht erinnere.

**Comment by LeSpocky** [comment]
In welchem Pull-Request?

**Comment by johannwagner** [comment]
https://github.com/FreifunkMD/site-ffmd/pull/93

```
GLUON_REGION
Some devices (at the moment the TP-Link Archer C7) contain a region code that restricts firmware installations. Set GLUON_REGION to eu or us to make the resulting images installable from the respective stock firmwares.
```
Aus https://gluon.readthedocs.io/en/v2017.1.x/user/getting_started.html#common-variables

**Comment by LeSpocky** [comment]
Ja jetzt seh ich's auch. Das gehört eigentlich in einen separaten PR und am besten bevor #93 gemerged wird.

**Comment by johannwagner** [comment]
Ich hab es da an der Stelle gesetzt, weil es in den Changes zur 2016.2.x noch extra erwähnt wurde, da einige Router Region Locks haben.

**Comment by johannwagner** [comment]
https://gluon.readthedocs.io/en/v2017.1.x/releases/v2016.2.html#site-mk

**Comment by LeSpocky** [comment]
Es ist schon Teil von v2016.1.x, daher denke ich, dass wir es vorher noch reinnehmen sollten: http://gluon.readthedocs.io/en/latest/releases/v2016.1.6.html

An der Stelle hätte ich gern wenigstens zwei getrennte Commits, wenn es schon im falschen PR auftaucht. 😉

**Comment by penguineer** [comment]
Pro zwei Commits, aber ich würde dafür keinen weiteren PR aufmachen. Das ist eine unserer Änderungen zur neuen Version. Kein Grund, das mit unnötigem Verwaltungsoverhead zu versehen.

**Comment by penguineer** [comment]
@johannwagner Wenn Du den Commit geteilt hast, schreib das hier mal bitte und schließe das Issue. Ich merge dann #93.

**Comment by johannwagner** [comment]
Commit ist auseinander gezogen. Ich halte es allerdings noch nicht für sinnvoll, die #93 zu mergen, da sie noch nicht mit der build.sh baut.

**Comment by penguineer** [comment]
Ah, dann schreib das bitte mal da rein. Ich schließe dieses Issue.
